export const FILTER_PRESET_NAMES = [
  "None",
  "Grayscale",
  "Sepia",
  "Vintage",
  "Kodachrome",
  "Polaroid",
  "Negative",
  "Technicolor",
  "Predator",
  "LSD",
  "Bright",
  "Contrast",
  "Night",
  "Blur Light",
  "Blur Heavy",
  "Noise Light",
  "Noise Heavy",
  "Alpha 50%",
  "Glow",
  "Bloom",
  "Drop Shadow",
  "Outline",
  "Pixelate",
  "RGB Split",
  "CRT",
  "Emboss",
  "Motion Blur",
  "Glitch",
  "Godray",
  "Bevel",
  "Cross Hatch",
  "Old Film",
  "ASCII",
  "Reflection",
  "Tilt Shift",
  "Zoom Blur",
  "Adjustment",
] as const;

export type FilterPresetName = (typeof FILTER_PRESET_NAMES)[number];
