import type { Manifest } from "../manifest";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore - dynamically generated by AssetPack
import _manifest from "../manifest.json";

const manifest = _manifest as Manifest;

const IMAGE_EXTS = [".png", ".jpg", ".jpeg", ".webp", ".svg"];
const VIDEO_EXTS = [".mp4", ".webm", ".m4v", ".ogv", ".mov"];
const GIF_EXT = ".gif";

export type PoolEntry = {
  key: string;
  type: "image" | "video" | "gif";
};

export function getProjectNames(): string[] {
  const names = new Set<string>();
  for (const bundle of manifest.bundles) {
    for (const asset of bundle.assets) {
      for (const src of asset.src) {
        const first = src.split("/")[0];
        if (first) names.add(first);
      }
    }
  }
  return [...names];
}

export function getProjectAssets(project: string): PoolEntry[] {
  const pool: PoolEntry[] = [];
  const seen = new Set<string>();
  const defaultBundle = manifest.bundles.find((b) => b.name === "default");
  const assets = defaultBundle?.assets ?? [];

  for (const asset of assets) {
    const firstSrc = asset.src[0];
    const lower = firstSrc.toLowerCase();
    const key = asset.alias[0] ?? firstSrc;

    if (seen.has(key)) continue;
    if (!key.startsWith(project)) continue;
    if (key.startsWith(`${project}/backgrounds/`)) continue;
    if (key.startsWith(`${project}/fix/`)) continue;

    if (IMAGE_EXTS.some((ext) => lower.endsWith(ext))) {
      seen.add(key);
      pool.push({ key, type: "image" });
    } else if (VIDEO_EXTS.some((ext) => lower.endsWith(ext))) {
      seen.add(key);
      pool.push({ key, type: "video" });
    } else if (lower.endsWith(GIF_EXT)) {
      seen.add(key);
      pool.push({ key, type: "gif" });
    }
  }
  return pool;
}

export function getProjectFixAssets(project: string): string[] {
  const aliases: string[] = [];
  for (const bundle of manifest.bundles) {
    for (const asset of bundle.assets) {
      const firstSrc = asset.src[0];
      if (!firstSrc.startsWith(`${project}/fix/`)) continue;
      const alias = asset.alias[0] ?? firstSrc;
      aliases.push(alias);
    }
  }
  return aliases;
}

export function getProjectBackgrounds(project: string): {
  videoAliases: string[];
  imageAliases: string[];
} {
  const videoAliases: string[] = [];
  const imageAliases: string[] = [];

  for (const bundle of manifest.bundles) {
    for (const asset of bundle.assets) {
      const firstSrc = asset.src[0];
      if (!firstSrc.startsWith(`${project}/backgrounds/`)) continue;

      const alias = asset.alias[0] ?? firstSrc;
      const ext = firstSrc.split(".").pop()?.toLowerCase();

      if (ext === "mp4" || ext === "webm" || ext === "ogg") {
        videoAliases.push(alias);
      } else if (
        ext === "png" ||
        ext === "jpg" ||
        ext === "jpeg" ||
        ext === "webp"
      ) {
        imageAliases.push(alias);
      }
    }
  }
  return { videoAliases, imageAliases };
}

export { manifest };
